name = "RandomUseful"
uuid = "86f72be6-8cd6-45b9-870f-803eaec04b8f"
authors = ["David AW Barton"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
